"""Thin runner-dispatch helpers exported through the tensor service surface."""

from __future__ import annotations

from typing import Any

import numpy as np

from lfptensorpipe.app.path_resolver import RecordContext

RUNTIME_PLAN_RUNNER_ATTRS = {
    "raw_power": "_run_raw_power_metric",
    "periodic_aperiodic": "_run_periodic_aperiodic_metric",
    "undirected_connectivity": "_run_undirected_connectivity_metric",
    "trgc_backend": "_run_trgc_backend_metric",
    "trgc_finalize": "_run_trgc_finalize_metric",
    "psi": "_run_psi_metric",
    "burst": "_run_burst_metric",
}


def _run_raw_power_metric(
    context: RecordContext,
    *,
    low_freq: float,
    high_freq: float,
    step_hz: float,
    mask_edge_effects: bool,
    bands: list[dict[str, Any]],
    selected_channels: list[str] | None,
    method: str = "morlet",
    time_resolution_s: float = 0.5,
    hop_s: float = 0.025,
    min_cycles: float | None = 3.0,
    max_cycles: float | None = None,
    time_bandwidth: float = 1.0,
    notches: Any = None,
    notch_widths: Any = 2.0,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
    read_raw_fif_fn=None,
    tfr_grid_fn=None,
    interpolate_freq_tensor_fn=None,
    load_tensor_filter_inheritance_fn=None,
) -> tuple[bool, str]:
    from .runners.raw_power import run_raw_power_metric

    return run_raw_power_metric(
        context,
        low_freq=low_freq,
        high_freq=high_freq,
        step_hz=step_hz,
        mask_edge_effects=mask_edge_effects,
        bands=bands,
        selected_channels=selected_channels,
        method=method,
        time_resolution_s=time_resolution_s,
        hop_s=hop_s,
        min_cycles=min_cycles,
        max_cycles=max_cycles,
        time_bandwidth=time_bandwidth,
        notches=notches,
        notch_widths=notch_widths,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
        read_raw_fif_fn=read_raw_fif_fn,
        tfr_grid_fn=tfr_grid_fn,
        interpolate_freq_tensor_fn=interpolate_freq_tensor_fn,
        load_tensor_filter_inheritance_fn=load_tensor_filter_inheritance_fn,
    )


def _run_periodic_aperiodic_metric(
    context: RecordContext,
    *,
    low_freq: float,
    high_freq: float,
    step_hz: float,
    mask_edge_effects: bool,
    bands: list[dict[str, Any]],
    selected_channels: list[str] | None,
    method: str = "morlet",
    time_resolution_s: float = 0.5,
    hop_s: float = 0.025,
    min_cycles: float | None = 3.0,
    max_cycles: float | None = None,
    time_bandwidth: float = 1.0,
    freq_range_hz: tuple[float, float] | None = None,
    freq_smooth_enabled: bool = True,
    freq_smooth_sigma: float | None = 1.5,
    time_smooth_enabled: bool = True,
    time_smooth_kernel_size: int | None = None,
    aperiodic_mode: str = "fixed",
    peak_width_limits_hz: tuple[float, float] = (2.0, 12.0),
    max_n_peaks: float = np.inf,
    min_peak_height: float = 0.0,
    peak_threshold: float = 2.0,
    fit_qc_threshold: float = 0.6,
    notches: Any = None,
    notch_widths: Any = 2.0,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
    read_raw_fif_fn=None,
    load_tensor_filter_inheritance_fn=None,
    compute_notch_intervals_fn=None,
    tfr_grid_fn=None,
    interpolate_freq_tensor_fn=None,
    smooth_axis_fn=None,
    decompose_fn=None,
    make_gof_rsquared_masker_fn=None,
) -> tuple[bool, str]:
    from .runners.periodic_aperiodic import run_periodic_aperiodic_metric

    return run_periodic_aperiodic_metric(
        context,
        low_freq=low_freq,
        high_freq=high_freq,
        step_hz=step_hz,
        mask_edge_effects=mask_edge_effects,
        bands=bands,
        selected_channels=selected_channels,
        method=method,
        time_resolution_s=time_resolution_s,
        hop_s=hop_s,
        min_cycles=min_cycles,
        max_cycles=max_cycles,
        time_bandwidth=time_bandwidth,
        freq_range_hz=freq_range_hz,
        freq_smooth_enabled=freq_smooth_enabled,
        freq_smooth_sigma=freq_smooth_sigma,
        time_smooth_enabled=time_smooth_enabled,
        time_smooth_kernel_size=time_smooth_kernel_size,
        aperiodic_mode=aperiodic_mode,
        peak_width_limits_hz=peak_width_limits_hz,
        max_n_peaks=max_n_peaks,
        min_peak_height=min_peak_height,
        peak_threshold=peak_threshold,
        fit_qc_threshold=fit_qc_threshold,
        notches=notches,
        notch_widths=notch_widths,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
        read_raw_fif_fn=read_raw_fif_fn,
        load_tensor_filter_inheritance_fn=load_tensor_filter_inheritance_fn,
        compute_notch_intervals_fn=compute_notch_intervals_fn,
        tfr_grid_fn=tfr_grid_fn,
        interpolate_freq_tensor_fn=interpolate_freq_tensor_fn,
        smooth_axis_fn=smooth_axis_fn,
        decompose_fn=decompose_fn,
        make_gof_rsquared_masker_fn=make_gof_rsquared_masker_fn,
    )


def _run_undirected_connectivity_metric(
    context: RecordContext,
    *,
    metric_key: str,
    connectivity_metric: str,
    low_freq: float,
    high_freq: float,
    step_hz: float,
    mask_edge_effects: bool,
    bands: list[dict[str, Any]],
    selected_channels: list[str] | None,
    selected_pairs: list[tuple[str, str]] | None,
    time_resolution_s: float = 0.5,
    hop_s: float = 0.025,
    method: str = "morlet",
    mt_bandwidth: float | None = None,
    min_cycles: float | None = 3.0,
    max_cycles: float | None = None,
    notches: Any = None,
    notch_widths: Any = 2.0,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
    read_raw_fif_fn=None,
    conn_grid_fn=None,
    interpolate_freq_tensor_fn=None,
    normalize_selected_pairs_fn=None,
    compute_notch_intervals_fn=None,
) -> tuple[bool, str]:
    from .runners.connectivity import run_undirected_connectivity_metric

    return run_undirected_connectivity_metric(
        context,
        metric_key=metric_key,
        connectivity_metric=connectivity_metric,
        low_freq=low_freq,
        high_freq=high_freq,
        step_hz=step_hz,
        mask_edge_effects=mask_edge_effects,
        bands=bands,
        selected_channels=selected_channels,
        selected_pairs=selected_pairs,
        time_resolution_s=time_resolution_s,
        hop_s=hop_s,
        method=method,
        mt_bandwidth=mt_bandwidth,
        min_cycles=min_cycles,
        max_cycles=max_cycles,
        notches=notches,
        notch_widths=notch_widths,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
        read_raw_fif_fn=read_raw_fif_fn,
        conn_grid_fn=conn_grid_fn,
        interpolate_freq_tensor_fn=interpolate_freq_tensor_fn,
        normalize_selected_pairs_fn=normalize_selected_pairs_fn,
        compute_notch_intervals_fn=compute_notch_intervals_fn,
    )


def _run_trgc_metric(
    context: RecordContext,
    *,
    low_freq: float,
    high_freq: float,
    step_hz: float,
    mask_edge_effects: bool,
    bands: list[dict[str, Any]],
    selected_channels: list[str] | None,
    selected_pairs: list[tuple[str, str]] | None,
    time_resolution_s: float = 0.5,
    hop_s: float = 0.025,
    method: str = "morlet",
    mt_bandwidth: float | None = None,
    min_cycles: float | None = 3.0,
    max_cycles: float | None = None,
    gc_n_lags: int = 20,
    group_by_samples: bool = False,
    round_ms: float = 50.0,
    notches: Any = None,
    notch_widths: Any = 2.0,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
    read_raw_fif_fn=None,
    normalize_selected_pairs_fn=None,
    compute_notch_intervals_fn=None,
    conn_grid_fn=None,
    interpolate_freq_tensor_fn=None,
) -> tuple[bool, str]:
    from .runners.connectivity import run_trgc_metric

    return run_trgc_metric(
        context,
        low_freq=low_freq,
        high_freq=high_freq,
        step_hz=step_hz,
        mask_edge_effects=mask_edge_effects,
        bands=bands,
        selected_channels=selected_channels,
        selected_pairs=selected_pairs,
        time_resolution_s=time_resolution_s,
        hop_s=hop_s,
        method=method,
        mt_bandwidth=mt_bandwidth,
        min_cycles=min_cycles,
        max_cycles=max_cycles,
        gc_n_lags=gc_n_lags,
        group_by_samples=group_by_samples,
        round_ms=round_ms,
        notches=notches,
        notch_widths=notch_widths,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
        read_raw_fif_fn=read_raw_fif_fn,
        normalize_selected_pairs_fn=normalize_selected_pairs_fn,
        compute_notch_intervals_fn=compute_notch_intervals_fn,
        conn_grid_fn=conn_grid_fn,
        interpolate_freq_tensor_fn=interpolate_freq_tensor_fn,
    )


def _run_trgc_backend_metric(
    context: RecordContext,
    *,
    backend_method: str,
    low_freq: float,
    high_freq: float,
    step_hz: float,
    bands: list[dict[str, Any]],
    selected_channels: list[str] | None,
    selected_pairs: list[tuple[str, str]] | None,
    time_resolution_s: float = 0.5,
    hop_s: float = 0.025,
    method: str = "morlet",
    mt_bandwidth: float | None = None,
    min_cycles: float | None = 3.0,
    max_cycles: float | None = None,
    gc_n_lags: int = 20,
    group_by_samples: bool = False,
    round_ms: float = 50.0,
    notches: Any = None,
    notch_widths: Any = 2.0,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
    read_raw_fif_fn=None,
    normalize_selected_pairs_fn=None,
    compute_notch_intervals_fn=None,
    conn_grid_fn=None,
    interpolate_freq_tensor_fn=None,
) -> tuple[bool, str]:
    from .runners.connectivity import run_trgc_backend_metric

    return run_trgc_backend_metric(
        context,
        backend_method=backend_method,
        low_freq=low_freq,
        high_freq=high_freq,
        step_hz=step_hz,
        bands=bands,
        selected_channels=selected_channels,
        selected_pairs=selected_pairs,
        time_resolution_s=time_resolution_s,
        hop_s=hop_s,
        method=method,
        mt_bandwidth=mt_bandwidth,
        min_cycles=min_cycles,
        max_cycles=max_cycles,
        gc_n_lags=gc_n_lags,
        group_by_samples=group_by_samples,
        round_ms=round_ms,
        notches=notches,
        notch_widths=notch_widths,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
        read_raw_fif_fn=read_raw_fif_fn,
        normalize_selected_pairs_fn=normalize_selected_pairs_fn,
        compute_notch_intervals_fn=compute_notch_intervals_fn,
        conn_grid_fn=conn_grid_fn,
        interpolate_freq_tensor_fn=interpolate_freq_tensor_fn,
    )


def _run_trgc_finalize_metric(
    context: RecordContext,
    *,
    mask_edge_effects: bool,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
) -> tuple[bool, str]:
    from .runners.connectivity import run_trgc_finalize_metric

    return run_trgc_finalize_metric(
        context,
        mask_edge_effects=mask_edge_effects,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
    )


def _run_psi_metric(
    context: RecordContext,
    *,
    low_freq: float,
    high_freq: float,
    step_hz: float,
    mask_edge_effects: bool,
    bands: list[dict[str, Any]],
    selected_channels: list[str] | None,
    selected_pairs: list[tuple[str, str]] | None,
    time_resolution_s: float = 0.5,
    hop_s: float = 0.025,
    method: str = "morlet",
    mt_bandwidth: float | None = None,
    min_cycles: float | None = 3.0,
    max_cycles: float | None = None,
    notches: Any = None,
    notch_widths: Any = 2.0,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
    read_raw_fif_fn=None,
    psi_grid_fn=None,
    normalize_selected_pairs_fn=None,
    compute_notch_intervals_fn=None,
) -> tuple[bool, str]:
    from .runners.connectivity import run_psi_metric

    return run_psi_metric(
        context,
        low_freq=low_freq,
        high_freq=high_freq,
        step_hz=step_hz,
        mask_edge_effects=mask_edge_effects,
        bands=bands,
        selected_channels=selected_channels,
        selected_pairs=selected_pairs,
        time_resolution_s=time_resolution_s,
        hop_s=hop_s,
        method=method,
        mt_bandwidth=mt_bandwidth,
        min_cycles=min_cycles,
        max_cycles=max_cycles,
        notches=notches,
        notch_widths=notch_widths,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
        read_raw_fif_fn=read_raw_fif_fn,
        psi_grid_fn=psi_grid_fn,
        normalize_selected_pairs_fn=normalize_selected_pairs_fn,
        compute_notch_intervals_fn=compute_notch_intervals_fn,
    )


def _run_burst_metric(
    context: RecordContext,
    *,
    low_freq: float,
    high_freq: float,
    step_hz: float,
    mask_edge_effects: bool,
    bands: list[dict[str, Any]],
    selected_channels: list[str] | None,
    percentile: float = 75.0,
    baseline_keep: list[str] | None = None,
    min_cycles: float = 2.0,
    max_cycles: float | None = None,
    hop_s: float | None = None,
    decim: int | None = None,
    thresholds: Any = None,
    notches: Any = None,
    notch_widths: Any = 2.0,
    thresholds_source_path: str | None = None,
    n_jobs: int = 1,
    outer_n_jobs: int = 1,
    read_raw_fif_fn=None,
    burst_grid_fn=None,
    compute_notch_intervals_fn=None,
) -> tuple[bool, str]:
    from .runners.burst import run_burst_metric

    return run_burst_metric(
        context,
        low_freq=low_freq,
        high_freq=high_freq,
        step_hz=step_hz,
        mask_edge_effects=mask_edge_effects,
        bands=bands,
        selected_channels=selected_channels,
        percentile=percentile,
        baseline_keep=baseline_keep,
        min_cycles=min_cycles,
        max_cycles=max_cycles,
        hop_s=hop_s,
        decim=decim,
        thresholds=thresholds,
        notches=notches,
        notch_widths=notch_widths,
        thresholds_source_path=thresholds_source_path,
        n_jobs=n_jobs,
        outer_n_jobs=outer_n_jobs,
        read_raw_fif_fn=read_raw_fif_fn,
        burst_grid_fn=burst_grid_fn,
        compute_notch_intervals_fn=compute_notch_intervals_fn,
    )


def invoke_runtime_plan_runner(
    svc: Any,
    context: RecordContext,
    *,
    runner_key: str,
    runner_kwargs: dict[str, Any],
    n_jobs: int,
    outer_n_jobs: int,
) -> tuple[bool, str]:
    runner_attr = RUNTIME_PLAN_RUNNER_ATTRS.get(str(runner_key))
    if not runner_attr:
        raise KeyError(f"Unsupported runtime plan runner: {runner_key}")
    runner = getattr(svc, runner_attr)
    kwargs = dict(runner_kwargs)
    kwargs["n_jobs"] = int(n_jobs)
    kwargs["outer_n_jobs"] = int(outer_n_jobs)
    return runner(context, **kwargs)


__all__ = [
    "RUNTIME_PLAN_RUNNER_ATTRS",
    "_run_burst_metric",
    "_run_periodic_aperiodic_metric",
    "_run_psi_metric",
    "_run_raw_power_metric",
    "_run_trgc_backend_metric",
    "_run_trgc_finalize_metric",
    "_run_trgc_metric",
    "_run_undirected_connectivity_metric",
    "invoke_runtime_plan_runner",
]
