reset_reference_defaults:
- anode: '0_7'
  cathode: '1_7'
  name: '0_1'
- anode: '1_7'
  cathode: '2_7'
  name: '1_2'
- anode: '2_7'
  cathode: '3_7'
  name: '2_3'
- anode: '8_15'
  cathode: '9_15'
  name: '8_9'
- anode: '9_15'
  cathode: '10_15'
  name: '9_10'
- anode: '10_15'
  cathode: '11_15'
  name: '10_11'
